# # CMAKE generated file: DO NOT EDIT!
# # Generated by "Unix Makefiles" Generator, CMake Version 3.27

# # Default target executed when no arguments are given to make.
# default_target: all
# .PHONY : default_target

# # Allow only one "make -f Makefile2" at a time, but pass parallelism.
# .NOTPARALLEL:

# #=============================================================================
# # Special targets provided by cmake.

# # Disable implicit rules so canonical targets will work.
# .SUFFIXES:

# # Disable VCS-based implicit rules.
# % : %,v

# # Disable VCS-based implicit rules.
# % : RCS/%

# # Disable VCS-based implicit rules.
# % : RCS/%,v

# # Disable VCS-based implicit rules.
# % : SCCS/s.%

# # Disable VCS-based implicit rules.
# % : s.%

# .SUFFIXES: .hpux_make_needs_suffix_list

# # Command-line flag to silence nested $(MAKE).
# $(VERBOSE)MAKESILENT = -s

# #Suppress display of executed commands.
# $(VERBOSE).SILENT:

# # A target that is always out of date.
# cmake_force:
# .PHONY : cmake_force

# #=============================================================================
# # Set environment variables for the build.

# # The shell in which to execute make rules.
# SHELL = /bin/sh

# # The CMake executable.
# CMAKE_COMMAND = /usr/bin/cmake

# # The command to remove a file.
# RM = /usr/bin/cmake -E rm -f

# # Escaping for special characters.
# EQUALS = =

# # The top-level source directory on which CMake was run.
# CMAKE_SOURCE_DIR = /home/elienai/Documentos/TEC/PROJETO_GAME/tec_prog_c-_game

# # The top-level build directory on which CMake was run.
# CMAKE_BINARY_DIR = /home/elienai/Documentos/TEC/PROJETO_GAME/tec_prog_c-_game

# #=============================================================================
# # Targets provided globally by CMake.

# # Special rule for the target edit_cache
# edit_cache:
# 	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
# 	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
# .PHONY : edit_cache

# # Special rule for the target edit_cache
# edit_cache/fast: edit_cache
# .PHONY : edit_cache/fast

# # Special rule for the target rebuild_cache
# rebuild_cache:
# 	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
# 	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
# .PHONY : rebuild_cache

# # Special rule for the target rebuild_cache
# rebuild_cache/fast: rebuild_cache
# .PHONY : rebuild_cache/fast

# # The main all target
# all: cmake_check_build_system
# 	$(CMAKE_COMMAND) -E cmake_progress_start /home/elienai/Documentos/TEC/PROJETO_GAME/tec_prog_c-_game/CMakeFiles /home/elienai/Documentos/TEC/PROJETO_GAME/tec_prog_c-_game//CMakeFiles/progress.marks
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
# 	$(CMAKE_COMMAND) -E cmake_progress_start /home/elienai/Documentos/TEC/PROJETO_GAME/tec_prog_c-_game/CMakeFiles 0
# .PHONY : all

# # The main clean target
# clean:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
# .PHONY : clean

# # The main clean target
# clean/fast: clean
# .PHONY : clean/fast

# # Prepare targets for installation.
# preinstall: all
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
# .PHONY : preinstall

# # Prepare targets for installation.
# preinstall/fast:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
# .PHONY : preinstall/fast

# # clear depends
# depend:
# 	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
# .PHONY : depend

# #=============================================================================
# # Target rules for targets named sfml-app

# # Build rule for target.
# sfml-app: cmake_check_build_system
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-app
# .PHONY : sfml-app

# # fast build rule for target.
# sfml-app/fast:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/build
# .PHONY : sfml-app/fast

# main.o: main.cpp.o
# .PHONY : main.o

# # target to build an object file
# main.cpp.o:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/main.cpp.o
# .PHONY : main.cpp.o

# main.i: main.cpp.i
# .PHONY : main.i

# # target to preprocess a source file
# main.cpp.i:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/main.cpp.i
# .PHONY : main.cpp.i

# main.s: main.cpp.s
# .PHONY : main.s

# # target to generate assembly for a file
# main.cpp.s:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/main.cpp.s
# .PHONY : main.cpp.s

# src/Ente.o: src/Ente.cpp.o
# .PHONY : src/Ente.o

# # target to build an object file
# src/Ente.cpp.o:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/Ente.cpp.o
# .PHONY : src/Ente.cpp.o

# src/Ente.i: src/Ente.cpp.i
# .PHONY : src/Ente.i

# # target to preprocess a source file
# src/Ente.cpp.i:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/Ente.cpp.i
# .PHONY : src/Ente.cpp.i

# src/Ente.s: src/Ente.cpp.s
# .PHONY : src/Ente.s

# # target to generate assembly for a file
# src/Ente.cpp.s:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/Ente.cpp.s
# .PHONY : src/Ente.cpp.s

# src/Entidade.o: src/Entidade.cpp.o
# .PHONY : src/Entidade.o

# # target to build an object file
# src/Entidade.cpp.o:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/Entidade.cpp.o
# .PHONY : src/Entidade.cpp.o

# src/Entidade.i: src/Entidade.cpp.i
# .PHONY : src/Entidade.i

# # target to preprocess a source file
# src/Entidade.cpp.i:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/Entidade.cpp.i
# .PHONY : src/Entidade.cpp.i

# src/Entidade.s: src/Entidade.cpp.s
# .PHONY : src/Entidade.s

# # target to generate assembly for a file
# src/Entidade.cpp.s:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/Entidade.cpp.s
# .PHONY : src/Entidade.cpp.s

# src/Gerenciador_Entradas.o: src/Gerenciador_Entradas.cpp.o
# .PHONY : src/Gerenciador_Entradas.o

# # target to build an object file
# src/Gerenciador_Entradas.cpp.o:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/Gerenciador_Entradas.cpp.o
# .PHONY : src/Gerenciador_Entradas.cpp.o

# src/Gerenciador_Entradas.i: src/Gerenciador_Entradas.cpp.i
# .PHONY : src/Gerenciador_Entradas.i

# # target to preprocess a source file
# src/Gerenciador_Entradas.cpp.i:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/Gerenciador_Entradas.cpp.i
# .PHONY : src/Gerenciador_Entradas.cpp.i

# src/Gerenciador_Entradas.s: src/Gerenciador_Entradas.cpp.s
# .PHONY : src/Gerenciador_Entradas.s

# # target to generate assembly for a file
# src/Gerenciador_Entradas.cpp.s:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/Gerenciador_Entradas.cpp.s
# .PHONY : src/Gerenciador_Entradas.cpp.s

# src/Jogador.o: src/Jogador.cpp.o
# .PHONY : src/Jogador.o

# # target to build an object file
# src/Jogador.cpp.o:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/Jogador.cpp.o
# .PHONY : src/Jogador.cpp.o

# src/Jogador.i: src/Jogador.cpp.i
# .PHONY : src/Jogador.i

# # target to preprocess a source file
# src/Jogador.cpp.i:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/Jogador.cpp.i
# .PHONY : src/Jogador.cpp.i

# src/Jogador.s: src/Jogador.cpp.s
# .PHONY : src/Jogador.s

# # target to generate assembly for a file
# src/Jogador.cpp.s:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/Jogador.cpp.s
# .PHONY : src/Jogador.cpp.s

# src/Personagem.o: src/Personagem.cpp.o
# .PHONY : src/Personagem.o

# # target to build an object file
# src/Personagem.cpp.o:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/Personagem.cpp.o
# .PHONY : src/Personagem.cpp.o

# src/Personagem.i: src/Personagem.cpp.i
# .PHONY : src/Personagem.i

# # target to preprocess a source file
# src/Personagem.cpp.i:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/Personagem.cpp.i
# .PHONY : src/Personagem.cpp.i

# src/Personagem.s: src/Personagem.cpp.s
# .PHONY : src/Personagem.s

# # target to generate assembly for a file
# src/Personagem.cpp.s:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/Personagem.cpp.s
# .PHONY : src/Personagem.cpp.s

# src/jogo.o: src/jogo.cpp.o
# .PHONY : src/jogo.o

# # target to build an object file
# src/jogo.cpp.o:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/jogo.cpp.o
# .PHONY : src/jogo.cpp.o

# src/jogo.i: src/jogo.cpp.i
# .PHONY : src/jogo.i

# # target to preprocess a source file
# src/jogo.cpp.i:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/jogo.cpp.i
# .PHONY : src/jogo.cpp.i

# src/jogo.s: src/jogo.cpp.s
# .PHONY : src/jogo.s

# # target to generate assembly for a file
# src/jogo.cpp.s:
# 	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml-app.dir/build.make CMakeFiles/sfml-app.dir/src/jogo.cpp.s
# .PHONY : src/jogo.cpp.s

# # Help Target
# help:
# 	@echo "The following are some of the valid targets for this Makefile:"
# 	@echo "... all (the default if no target is provided)"
# 	@echo "... clean"
# 	@echo "... depend"
# 	@echo "... edit_cache"
# 	@echo "... rebuild_cache"
# 	@echo "... sfml-app"
# 	@echo "... main.o"
# 	@echo "... main.i"
# 	@echo "... main.s"
# 	@echo "... src/Ente.o"
# 	@echo "... src/Ente.i"
# 	@echo "... src/Ente.s"
# 	@echo "... src/Entidade.o"
# 	@echo "... src/Entidade.i"
# 	@echo "... src/Entidade.s"
# 	@echo "... src/Gerenciador_Entradas.o"
# 	@echo "... src/Gerenciador_Entradas.i"
# 	@echo "... src/Gerenciador_Entradas.s"
# 	@echo "... src/Jogador.o"
# 	@echo "... src/Jogador.i"
# 	@echo "... src/Jogador.s"
# 	@echo "... src/Personagem.o"
# 	@echo "... src/Personagem.i"
# 	@echo "... src/Personagem.s"
# 	@echo "... src/jogo.o"
# 	@echo "... src/jogo.i"
# 	@echo "... src/jogo.s"
# .PHONY : help



# #=============================================================================
# # Special targets to cleanup operation of make.

# # Special rule to run CMake to check the build system integrity.
# # No rule that depends on this can have commands that come from listfiles
# # because they might be regenerated.
# cmake_check_build_system:
# 	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
# .PHONY : cmake_check_build_system

clean:
	rm -rf build/*
